

// Adjust the path if your globals.css is in a different folder
import { Footer, NavigationBar } from "./components/componentsBarrel";
import "./styles/global.css"; 
import 'bootstrap/dist/css/bootstrap.min.css';



export const metadata = {
    title: 'CoinMaster',
    description: 'Generated by create next app',
}

// React component for the layout
// children is a prop or property 
// Layout components wraps page components in `Next.js`
export default function RootLayout({ children }) {
    return (
        <html lang="en">       
            <body className="content">
            <NavigationBar/>
            {children}
            <Footer/>  
            </body>
        </html>
    )
}
