

// Adjust the path if your globals.css is in a different folder
import WalletProvider from '../app/components/providers/WalletProvider';
import { NavigationBar } from "./components/componentsBarrel";
import { Footer } from "./components/componentsBarrel";
import "./styles/global.css"; 
import 'bootstrap/dist/css/bootstrap.min.css';
import { Roboto } from '@next/font/google';


// Roboto Configuration
const roboto = Roboto({
    subsets: ['latin'],
    weight: ['400', '700', '900'],
});



export const metadata = {
    title: 'CoinMaster',
    description: 'Generated by create next app',
}

// React component for the layout
// children is a prop or property 
// Layout components wraps page components in `Next.js`
export default function RootLayout({ children }) {
    return (
        <html lang="en">     
          
            <body className={roboto.className}>
            <NavigationBar/>
            <div className="content">
            <WalletProvider>
            {children}
            </WalletProvider>
            <Footer/> 
            </div>
            </body>
        </html>
    )
}
